/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.core.jooq;


import io.github.onotoliy.core.jooq.tables.TreasureException;
import io.github.onotoliy.core.jooq.tables.TreasureLog;
import io.github.onotoliy.core.jooq.tables.records.TreasureExceptionRecord;
import io.github.onotoliy.core.jooq.tables.records.TreasureLogRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TreasureExceptionRecord> TREASURE_EXCEPTION_PKEY = Internal.createUniqueKey(TreasureException.TREASURE_EXCEPTION, DSL.name("treasure_exception_pkey"), new TableField[] { TreasureException.TREASURE_EXCEPTION.GUID }, true);
    public static final UniqueKey<TreasureLogRecord> TREASURE_LOG_PKEY = Internal.createUniqueKey(TreasureLog.TREASURE_LOG, DSL.name("treasure_log_pkey"), new TableField[] { TreasureLog.TREASURE_LOG.GUID }, true);
}
