/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.core.jooq;


import io.github.onotoliy.core.jooq.tables.CoreDeviceException;
import io.github.onotoliy.core.jooq.tables.CoreLog;
import io.github.onotoliy.core.jooq.tables.records.CoreDeviceExceptionRecord;
import io.github.onotoliy.core.jooq.tables.records.CoreLogRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CoreDeviceExceptionRecord> PK_CORE_DEVICE_EXCEPTION = Internal.createUniqueKey(CoreDeviceException.CORE_DEVICE_EXCEPTION, DSL.name("PK_CORE_DEVICE_EXCEPTION"), new TableField[] { CoreDeviceException.CORE_DEVICE_EXCEPTION.GUID }, true);
    public static final UniqueKey<CoreLogRecord> PK_CORE_LOG = Internal.createUniqueKey(CoreLog.CORE_LOG, DSL.name("PK_CORE_LOG"), new TableField[] { CoreLog.CORE_LOG.GUID }, true);
}
