/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.core.jooq;


import io.github.onotoliy.core.jooq.tables.TreasureException;
import io.github.onotoliy.core.jooq.tables.TreasureLog;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Описание ошибки устройства
     */
    public final TreasureException TREASURE_EXCEPTION = TreasureException.TREASURE_EXCEPTION;

    /**
     * Логи
     */
    public final TreasureLog TREASURE_LOG = TreasureLog.TREASURE_LOG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            TreasureException.TREASURE_EXCEPTION,
            TreasureLog.TREASURE_LOG);
    }
}
