/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.core.jooq;


import io.github.onotoliy.core.jooq.tables.TreasureException;
import io.github.onotoliy.core.jooq.tables.TreasureLog;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Описание ошибки устройства
     */
    public static final TreasureException TREASURE_EXCEPTION = TreasureException.TREASURE_EXCEPTION;

    /**
     * Логи
     */
    public static final TreasureLog TREASURE_LOG = TreasureLog.TREASURE_LOG;
}
