/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.core.jooq;


import io.github.onotoliy.core.jooq.tables.CoreDeviceException;
import io.github.onotoliy.core.jooq.tables.CoreLog;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Описание ошибки устройства
     */
    public static final CoreDeviceException CORE_DEVICE_EXCEPTION = CoreDeviceException.CORE_DEVICE_EXCEPTION;

    /**
     * Логи
     */
    public static final CoreLog CORE_LOG = CoreLog.CORE_LOG;
}
